spring:
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: false

#myapp:
#  signinkey: ${env.SIGNIN_KEY}
#  expirationtime: ${env.EXPIRATION_TIME}
#  refreshsigninkey: ${env.REFRESH_SIGNING_KEY}
#  refreshexpirationtime: ${env.REFRESH_EXPIRATION_TIME}
